name: deploy
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: init ssh, deploy
        run: |
          eval $(ssh-agent -s)
          echo "${{secrets.PRIVATE_KEY}}" > deploy.key
          mkdir -p ~/.ssh
          chmod 0600 deploy.key
          ssh-add deploy.key
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          scp sh/restart.sh ${{secrets.HOST_NAME}}@${{secrets.KLEIN_HOST}}:~/crv_sh/
          scp docker-compose.yml ${{secrets.HOST_NAME}}@${{secrets.KLEIN_HOST}}:~/crv_sh/
          ssh ${{secrets.HOST_NAME}}@${{secrets.KLEIN_HOST}} "cd crv_sh && sh restart.sh"